routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\User;
use App\Admin;
use Illuminate\Support\Facades\Redis;
use App\Events\UserEvent;
Route::get('/search','SearchController@search');
Route::post('users/logout','Auth\LoginController@userLogout')->name('users.logout');
Route::group(['namespace' => 'Auth'],function (){
    Route::get('/redirect', 'SocialAuthFacebookController@redirect');
    Route::get('/callback', 'SocialAuthFacebookController@callback');
});
Route::group(['prefix' => 'admin','namespace'=>'Admin'], function() {
    Route::get('/','HomeController@index')->name('admin.dashboard');
    Route::get('/login','LoginController@showLoginForm');
    Route::get('/junks','JunkController@index')->name('junk');

    Route::post('/junks/status/{id}','JunkController@status')->name('status');
    // Route::get('/category','JunkController@category')->name('')
    Route::get('/users','UserController@index')->name('users');
    Route::post('/login','LoginController@login')->name('admin.login');
    Route::post('/logout','LoginController@logout')->name('admin.logout');
    Route::resource('/fixcat', 'FixCatController',['only' =>['create','update','destroy','index','store']]);
    Route::resource('/clients', 'ClientController',['only' =>['create','update','destroy','index','store']]);
    Route::resource('/partners', 'PartnerController',['only' => ['create','update','destroy','index','store']]);
    Route::resource('/testimonials', 'TestimonialController',['only' => ['create','update','destroy','index','store']]);
    Route::delete('/{user}/notifications',function (Admin $admin){
        return $admin->notifications->delete();
    });
});
Auth::routes();

// @todo - make a more decent route with category and name
Route::get('/', 'HomeController@index')->name('home');
Route::get('/junk/{category}/{junk}','HomeController@show')->name('junk');
Route::post('/junk/{id}/view', 'HomeController@view')->name('view');
Route::group(['prefix' => 'junk','namespace' => 'User'], function(){
    Route::get('/sell','JunkController@sell')->name('sell.junk');
    Route::post('/sell','JunkController@sellJunk')->name('sell');
    Route::get('/{fixcat}','JunkController@junkCategory')->where(['fixcat' => '[A-Za-z_-]+'])->name('junk.category');
});




// All routings for the users
Route::group(['prefix' => 'user','namespace' => 'User'],function(){
	Route::get('/','DashboardController@index')->name('users.dashboard');

    Route::resource('/user-profile','ProfileController',['only' => ['show','update']]);
    Route::resource('/junks','JunkController',['only' => ['create','update','destroy','index','store']]);
    Route::get('/junks/category','JunkController@category');
    Route::post('/user-profile/image/{id}','ProfileController@image');


});

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.admin')
@section('content')                       <!-- /.section -->
@endsection

resources/views/admin/fixcat-manager.blade.php
<div class="main-page">
    <div class="container-fluid">
        <div class="row page-title-div">
            <div class="col-md-6">
                <h2 class="title">Smart Fix Category</h2>
            </div>
            <!-- /.col-md-6 -->
            <!-- /.col-md-6 text-right -->
        </div>
        <!-- /.row -->
        <div class="row breadcrumb-div">
            <div class="col-md-6">
                <ul class="breadcrumb">
					<li><a href="index.html"><i class="fa fa-home"></i> Home</a></li>
					<li><a href="#">dashboard</a></li>
					<li class="active">FixCat Manager</li>
				</ul>
            </div>
            <!-- /.col-md-6 -->
            <div class="col-md-6 text-right">
                <a href="#"><i class="fa fa-comments"></i> Talk to us</a>
                <a href="#" class="pl-20"><i class="fa fa-cog"></i> Settings</a>
            </div>
            <!-- /.col-md-6 -->
        </div>
                            <!-- /.row -->
    </div>
                        <!-- /.container-fluid -->

    <section class="section">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h5 >Add a category to the Smart Fix</h5>
                            </div>
                        </div>
                        <div class="panel-body">

                            <form id="catAdd" method="POST" action="{{route('fixcat.store')}}">
                            {{ csrf_field() }}
                                <div class="form-group">
                            		<label for="name">Smart Fix Category name</label>
                            		<input type="text" name ="name" class="form-control" id="name" placeholder="Category name">
                            	</div>
                            

                            	<button id="cli" type="submit" class="btn btn-primary">Add</button>
                            </form>

                            
                            <!-- /.col-md-12 -->
                        </div>
                    </div>
                </div>
                <!-- /.col-md-6 -->
                    
                
                <!-- /.col-md-6 -->
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="panel">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h5>Available Category</h5>
                            </div>
                        </div>
                        <div class="panel-body">

                            <div class="list-group">
                            <li class="list-group-item">Cras justo odio</li>
                                
                                
                            </div>

                           
                            <!-- /.col-md-12 -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container-fluid -->
    </section>
</div>

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>SmartFix- Login</title>

        <!-- ========== COMMON STYLES ========== -->
        <link rel="stylesheet" href="{{asset('css/admin/bootstrap.min.css')}}" media="screen" >
        <link rel="stylesheet" href="{{asset('css/admin/font-awesome.min.css')}}" media="screen" >
        <link rel="stylesheet" href="{{asset('css/admin/animate-css/animate.min.css')}}" media="screen" >

        <!-- ========== PAGE STYLES ========== -->
        <link rel="stylesheet" href="{{asset('css/admin/icheck/skins/flat/blue.css')}}" >

        <!-- ========== THEME CSS ========== -->
        <link rel="stylesheet" href="{{asset('css/admin/main.css')}}" media="screen" >

        <!-- ========== MODERNIZR ========== -->
        <script src="{{asset('js/modernizr/modernizr.min.js')}}"></script>
    </head>
    <body class="">
        <div class="main-wrapper">

            <div class="login-bg-color bg-black-300">
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <div class="panel login-box">
                            <div class="panel-heading">
                                <div class="panel-title text-center">
                                    <h4>Smart Fix Admin Login</h4>
                                </div>
                            </div>
                            <div class="panel-body p-20">

                                <form method="POST" action="{{ route('admin.login')}}">
                                {{ csrf_field() }}
                                	<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                		<label for="email">Email address</label>
                                        <input type="email" class="form-control" placeholder="Enter Your Email Id" name="email" value="{{ old('email') }}" required autofocus >
                                         @if ($errors->has('email'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('email') }}</strong>
                                            </span>
                                        @endif
                                	</div>
                                	<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                                		<label for="password">Password</label>
                                		<input type="password" class="form-control"  placeholder="Password" name="password" required>
                                         @if ($errors->has('password'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('password') }}</strong>
                                            </span>
                                        @endif
                                	</div>
                                    <div class="checkbox op-check">
                                        <label>
                                            <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }} class="flat-blue-style"> <span class="ml-10">Remember me</span>
                                        </label>
                                    </div>
                                    <div class="form-group mt-20">
                                        <div class="">
                                            <a href="#" class="form-link"><small class="muted-text">Forgot Password?</small></a>
                                            <button type="submit" class="btn btn-success btn-labeled pull-right">Sign in<span class="btn-label btn-label-right"><i class="fa fa-check"></i></span></button>
                                            <div class="clearfix"></div>
                                        </div>
                                    </div>
                                    
                                </form>

                                
                                <!-- /.text-center -->

                            
                                <!-- /.text-center -->

                            </div>
                        </div>
                        <!-- /.panel -->
                        <p class="text-muted text-center"><small>Copyright © SmartFix 2017</small></p>
                    </div>
                    <!-- /.col-md-6 col-md-offset-3 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /. -->

        </div>
        <!-- /.main-wrapper -->

        <!-- ========== COMMON JS FILES ========== -->
        <script src="{{asset('js/jquery/jquery-2.2.4.min.js')}}"></script>
        <script src="{{asset('js/jquery-ui/jquery-ui.min.js')}}"></script>
        <script src="{{asset('js/bootstrap/bootstrap.min.js')}}"></script>
        <script src="{{asset('js/pace/pace.min.js')}}"></script>
        <script src="{{asset('js/lobipanel/lobipanel.min.js')}}"></script>
        <script src="{{asset('js/iscroll/iscroll.js')}}"></script>

        <!-- ========== PAGE JS FILES ========== -->
        <script src="{{asset('js/icheck/icheck.min.js')}}"></script>

        <!-- ========== THEME JS ========== -->
        <script src="js/main.js"></script>
        <script>
            $(function(){
                $('input.flat-blue-style').iCheck({
                    checkboxClass: 'icheckbox_flat-blue'
                });
            });
        </script>

        <!-- ========== ADD custom.js FILE BELOW WITH YOUR CHANGES ========== -->
    </body>
</html>